"""empty message

Revision ID: fb523cc77de7
Revises: 
Create Date: 2022-09-13 18:36:06.479806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb523cc77de7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('domain_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_group_title'), 'domain_group', ['title'], unique=True)
    op.create_table('domain_ssl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('issuer', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=1000), nullable=True),
    sa.Column('tls_version', sa.String(length=32), nullable=True),
    sa.Column('cert', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('expire_date', sa.String(length=32), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('describe', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_ssl_domain'), 'domain_ssl', ['domain'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('pc_addr', sa.String(length=32), nullable=True),
    sa.Column('mobile_addr', sa.String(length=32), nullable=True),
    sa.Column('is_points', sa.Boolean(), nullable=True),
    sa.Column('is_ssl', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('ssl_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['domain_group.id'], ),
    sa.ForeignKeyConstraint(['ssl_id'], ['domain_ssl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_domain'), 'domain', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_domain'), table_name='domain')
    op.drop_table('domain')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_domain_ssl_domain'), table_name='domain_ssl')
    op.drop_table('domain_ssl')
    op.drop_index(op.f('ix_domain_group_title'), table_name='domain_group')
    op.drop_table('domain_group')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
